# Site settings
title: Megan and Grant's Adventures
header-img: img/MonteSano.jpg
email: megkearl@gmail.com
copyright_name: Grant and Megan
description: "Megan and Grant's Travel Adventures"
baseurl: "/adventures"
url: "http://adventures.meganandgrant.com"
twitter_username: makearl
github_username:  makearl
#facebook_username:  StartBootstrap
email_username:  megkearl@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-87819650-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
